### PR TITLE
Handle transaction numbers

### PR DESCRIPTION
**Pull request by timcullen**
I have a qif file which contains 'N' type lines which contain details about the transaction number (typically a cheque/check number.  The change here captures that tag rather than throwing an error.

### CODE REVIEW

**Comment by spmason** [comment]
Looks like this is failing part of the Travis build. To be fair, the node versions in travis.yml need updating anyway

I can do that when I get some time (currently away from my laptop), or feel free to tack onto this pr

**Comment by timcullen** [comment]
Can't see anything obviously wrong, but Travis not my forte!

**Comment by spmason** [comment]
I've fixed the build on master - if you rebase this PR it should be fine

Can you also write a [unit test](https://github.com/spmason/qif2json/blob/master/test/qif2json.tests.js) for this new field?

**Comment by timcullen** [comment]
Will do. Probably tomorrow morning. Thanks Steve 


Tim

**Comment by spmason** [comment]
Actually, I just started adding support for all the example docs from https://www.w3.org/2000/10/swap/pim/qif-doc/QIF-doc.htm - which involved adding in `N`, so I'm going to close this

Thanks for bringing to my attention though, feel free to open issues/prs for anything else you find

**Pull request closed without merging**
